### ISSUE TITLE
Test incorrectly reports missing image due to default suffixes

### ISSUE THREAD

**Issue by dcaunt** [facebook/ios-snapshot-test-case#102]
I'm new to version 2 of ios-snapshot-test-case so please forgive me if I've misunderstood how the suffixes are intended to work.

I've created a simple test which renders one of my custom UIView objects with a frame of size (50,50). I run the test on the iPhone 6 simulator with `recordMode` set to `YES` and it creates the expected reference image in the `ReferenceImages_64` directory.

When I set `recordMode` to `NO` and change an attribute of the view, such as the frame, the test fails with the following error: `Reference image not found. You need to run the test in record mode` 

The reason it fails because there is an error matching against the snapshot in `ReferenceImages_64` (which exists), and so it continues with the next suffix (`_32`) and the final error returned is that a reference image does not exist in `ReferenceImages_32`.

Of course, if I force a set of suffixes with a single suffix string, my tests work as expected and I get the correct error message, `NSLocalizedFailureReason=referenceImage:{50, 50}, image:{150, 50}}`.

I would expect the error returned to be the first error encountered which is not an instance of `FBSnapshotTestControllerErrorCodeNeedsRecord`.

It seems to me that the [macro loop here](https://github.com/facebook/ios-snapshot-test-case/blob/29bc87aaa8a3eb89bc42b07626f590bc859b674e/FBSnapshotTestCase/FBSnapshotTestCase.h#L33-L37) should check the error code and break for the different size/different image cases.

Let me know if I can help with a PR for this or please point out where I'm going wrong.

**Comment by nscoding** [comment]
Nice thank you filling this issue, you are right and I would welcome a PR to make this better.

**Comment by dcaunt** [comment]
I've had a quick look at a PR and we'll need to expose `FBSnapshotTestControllerErrorCode` – where do you want to put it?

Also, is there a benefit in using macros over C functions?

**Comment by nscoding** [comment]
Just to clarify the `for` loop there is intended.

The idea behind this is to check for the 64bit image. If there is none or is different, then load the 32bit image and compare before failing completely (and vice versa). We did this because we run tests for both architectures but most of the snapshots are the same. They differ when text is involved (antialiasing).

IMO, what can be improved here is the following:

- 32bit has no images
- 64bit has no images
- Run the test on 64bit with `recordMode = NO;`
- Test fails and mentions that 32bit snapshot is missing, while it should point out that the test was running in 64bit.

**Comment by soleares** [comment]
+1

**Comment by Grubas7** [comment]
The problem is in define `FBSnapshotVerifyViewOrLayerWithOptions()` and `for` loop. This loops iterate on resources path with sufixes {_64, _32}. If you have snapshot with some view, but comparation fails (so sets variable `error`), loops goes to next sufix and if you don't have valid snapshot for other architecture comparation fails again set error one more time. So we are losing value of first `error` and have wrong error which says we don't have snapshot for other architecture.

I'll make pull request on next days.

**Comment by nscoding** [comment]
@Grubas7 correct, a PR would be really awesome!

**Comment by Grubas7** [comment]
I found solution for this issue ;)
I made commit, but (I hope) tomorrow I'll write missing documentation for one method which I made public. Also I'll explain code, which may look a bit chaotic (but it is not!), and write possible test scenarios.

**Comment by Grubas7** [comment]
PR for issue #119 

Tests cases:
- recordMode = 1, no reference images, run on 32bit or 64bit architecture simulator.

Test case failed:

> ((self.recordMode) is false) failed - Test ran in record mode. Reference image is now saved. Disable record mode to perform an actual snapshot comparison!

- recordMode = 1, with reference images, run on 32bit or 64bit architecture simulator.

Test case failed:

>((self.recordMode) is false) failed - Test ran in record mode. Reference image is now saved. Disable record mode to perform an actual snapshot comparison!

- recordMode = 0, no reference images, run on 32bit or 64bit architecture simulator.

Test case failed:
No image found for 64bit **and** 32bit architecture (error order depends of currently used simulator)

>"Error Domain=FBSnapshotTestControllerErrorDomain Code=1 \"Unable to load reference image.\" UserInfo=0x7fce83d49be0 {NSLocalizedFailureReason=Reference image not found. You need to run the test in record mode, NSLocalizedDescription=Unable to load reference image., FBReferenceImageFilePathKey=.../FBSnapshotTestCaseDemo/FBSnapshotTestCaseDemoTests/ReferenceImages_**64**/FBSnapshotTestCaseDemoTests/testViewSnapshot@2x.png}",
__
"Error Domain=FBSnapshotTestControllerErrorDomain Code=1 \"Unable to load reference image.\" UserInfo=0x7fce83d4e230 {NSLocalizedFailureReason=Reference image not found. You need to run the test in record mode, NSLocalizedDescription=Unable to load reference image., FBReferenceImageFilePathKey=.../FBSnapshotTestCaseDemo/FBSnapshotTestCaseDemoTests/ReferenceImages_**32**/FBSnapshotTestCaseDemoTests/testViewSnapshot@2x.png}"

- recordMode = 0, with **valid** reference image _64, run on 64bit architecture simulator, or with **valid** reference image _32, run on 32bit architecture simulator.

Test case passed.

If simulator found valid reference image in his architecture won't look for other image.
Sometimes one architecture might have difference UI from other (eg. iPad 2 has disabled native blur effect support), so if found valid image for active architecture then shouldn't look other image.

- recordMode = 0, with **valid** reference image _64, run on 32bit architecture simulator, or with **valid** reference image _32, run on 64bit architecture simulator.

Test case passed.

If simulator didn't find reference image for his architecture, will look for reference image in other architecture folder.

- recordMode = 0, with **invalid** reference image _64 and/or _32, run on 32bit and/or 64bit architecture simulator.

Test case failed.

>"Error Domain=FBSnapshotTestControllerErrorDomain Code=4 \"Images different\" UserInfo=0x7be187f0 {NSLocalizedDescription=Images different}"

If simulator found reference image for his architecture, but it's invalid, won't look for reference image in other architecture folder, because UI has changes.

**Comment by nscoding** [comment]
Thanks for fixing this @Grubas7
