### ISSUE TITLE
Some images recorded on 32 bit simulator will result in test failure on 64 bit devices

### ISSUE THREAD

**Issue by grantjk** [facebook/ios-snapshot-test-case#21]
I'm not sure what is causing this or if it would be fixed by #19.

For some of our snapshot tests, if we record them on the 32 bit simulator and then immediately run it back in the 64 bit simulator, it results in a test failure - but there's no visible difference in the images.  Same if we record in 64 bit and test in 32 bit. This doesn't happen for every image, but for the images it does fail, it is consisten.

As a result, our Xcode bot reports failures for the other architecture.

Any ideas what would be causing this or how I could address this?

**Comment by stkhapugin** [comment]
I've ran into similar issues. No colors involved: I've checked my views in black and white. Indeed, autolayout's non-integral coordinates get rounded differently on 32 and 64 bit architectures. This is especially noticeable when laying out something with UILabels. 
One possible workaround I see is to NOT use labels in tested views. This should account for text rendering nuances. 
Personally I don't think that adding suffices is an elegant solution. 

I have also spent several hours on this issue today unitl I found this *closed* thread. I think it would be very nice to add **some kind of disclaimer** about this (as @dblock mentioned before), because I am definitely not the only one who will have this problem in the future.

If necessary, I will gladly provide failing snapshots and a test project to illustrate the issue.

Thanks for the awesome testing tool, though!
