### ISSUE TITLE
Allow approximate comparison with a margin of error

### ISSUE THREAD

**Issue by dblock** [facebook/ios-snapshot-test-case#38]
Check out https://github.com/aleph7/AIImageCompare, it supports mean image comparison where you don't have to have exactly identical images. This may be useful for cases where there're, say, anti-aliasing marginal errors in image comparison.

**Comment by itsthejb** [comment]
:+1:

**Comment by kerrmarin** [comment]
:+1:

**Comment by Dionysiac** [comment]
This would be very useful.
We are seeing repeated test failures across different machines where the failure is from a single pixel difference within the gradient of anti-aliased text.

**Comment by nap-sam-dean** [comment]
:+1:

**Comment by nap-sam-dean** [comment]
Morning everyone.

I've taken a first stab at this here : https://github.com/nap-sam-dean/ios-snapshot-test-case but have run into a problem. It works absolutely fine but I can't find a way to get the build.sh to build the library. It builds the demo project fine because that has gone and got the AIImageCompare pod to link against but the project in the root folder doesn't do that.

Any ideas round that? (The other option is to roll my own 'image compare with margin of error' method; it's not difficult but it seems wasteful if someone else has already done the work?

**Comment by nap-sam-dean** [comment]
Hi everyone. I've made a pull request - if you case, take a look :) https://github.com/facebook/ios-snapshot-test-case/pull/86

**Comment by nscoding** [comment]
:clap: this is now in master thanks to @nap-sam-dean and his awesome PR. (#86)
