### ISSUE TITLE
Problem with retina compare (2.0.x) 

### ISSUE THREAD

**Issue by x2on** [facebook/ios-snapshot-test-case#95]
Hi,

since 2.0 the compare doesn't work here anymore.
I assume that the change in `UIImage+Diff.m` causes the problem.

Why is the following code removed? 
```objective-c
CGFloat scaleFactor = [[UIScreen mainScreen] scale];		
CGContextScaleCTM(referenceImageContext, scaleFactor, scaleFactor);		
CGContextScaleCTM(imageContext, scaleFactor, scaleFactor);
```

Without this it doesn't work here anymore.

**Comment by nscoding** [comment]
I will check it today, it was removed because it was breaking the approximation comparison I believe.

cc @nap-sam-dean

**Comment by nap-sam-dean** [comment]
It was debated and removed because it was breaking the compare tests on retina devices - the rendered images were wrong and we decided that it wasn't needed because the pixel counts were already correct.

However, it looks like it wasn't as harmless a change as we expected :) 

Do you have a test image/s that we can compare to see why it's broken now?

**Comment by nscoding** [comment]
I see, I think the problem is [here](https://github.com/facebook/ios-snapshot-test-case/blob/master/FBSnapshotTestCase/UIImage%2BCompare.m#L88-L89), we should be using `CGImageGetWidth()` and `CGImageGetHeight()`.

I will open a PR shortly.

**Comment by nscoding** [comment]
@x2on Do you want to patch #96 and give it a try? I am confident that this was the issue but just to make sure. Thank you for your time.

**Comment by x2on** [comment]
I will have a look at this!

**Comment by x2on** [comment]
@nscoding #96 works fine for my projects! Thanks!

**Comment by nscoding** [comment]
Thank you very much for opening this issue and helping out.
